### ISSUE TITLE
ReadStream: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by dolanmiu** [isaacs/node-graceful-fs#109] opened 2017-03-11 21:39 UTC
I am getting this issue:

https://github.com/isaacs/node-graceful-fs/issues/70

On these lines:

https://github.com/isaacs/node-graceful-fs/blob/master/graceful-fs.js#L165-L166

```js
var fs$ReadStream = fs.ReadStream // ReadStream is undefined!
ReadStream.prototype = Object.create(fs$ReadStream.prototype)
```

But I am **NOT** on Meteor. I am using Angular2

**Comment by danielbaak** [comment] 2017-04-03 12:36
I can confirm the issue.  
Apparently `fs` contains only fs.FileReadStream (and fs.FileWriteStream) which may (?) be meant.

**Comment by iMasterAle** [comment] 2017-05-29 16:46
I have the same problem

**Comment by ernieyang09** [comment] 2017-06-01 11:53
same here,using webpack2 & react

**Comment by haredev** [comment] 2017-06-19 22:06
+1 having this issue

**Comment by loperto** [comment] 2017-06-29 20:36
i have the same problem with react and webpack

**Comment by chackerian** [comment] 2017-06-30 08:46
I have the same problem as well when trying to require mongodb

**Comment by optiguy** [comment] 2017-07-02 04:37
I have the same problem with create-react-app

**Comment by Sl0w87** [comment] 2017-07-05 14:39
I have the same issue with a clean project that i created with create-react-app.
As i use chokidar in the App component i get this error on yarn start.

**Comment by lafiza** [comment] 2017-07-18 13:08
+1 having same issue

**Comment by Sl0w87** [comment] 2017-07-19 09:21
Hi all,
i have fixed my issue.
The problem was, that i have created an electron app in that i used react.
If you want to use chokidar in this constelation, you must import ist with the following code:
`const chokidar = window.require('chokidar');`

Maybe anyone has the same constelation and problem.

**Comment by sjbwylbs** [comment] 2017-08-13 16:36
i have same issue.
i have fixed my issue.

```bash
npm i chalk@2.0.1
```
it work fine.

i think it would help some one!

**Comment by medkhelifi** [comment] 2017-09-07 21:28
I have the same problem;
React + Webpack 2
In webpack config, I added 
`node: {
        fs: 'empty'
    }`
But the issue still remains.

**Comment by sjbwylbs** [comment] 2017-09-26 02:14
@medkhelifi did't you try replace your chalk version to 2.0.1？

**Comment by gemma-ferreras** [comment] 2018-02-05 11:42
I am having the same issue. Any updates? I used create-react-app ejected it.

**Comment by genachka** [comment] 2018-02-07 22:31
+1

**Comment by sirentek** [comment] 2018-02-17 22:08
using electron with nodejs.
same here..

updating chalk version to 2.0.1 => did not work for me.
updating chalk version to 2.3.1 => did not work for me either.

**Comment by dmftuva** [comment] 2018-02-21 07:43
with FS you are trying to get file from clients computer? fs must be used on back ) no webpack

**Comment by AnelaNuo** [comment] 2018-06-16 18:16
Dear Isaacs,
Could you close issues #121 and this after fixing this bug.
I tried to rewrite two last lines in your code by the above pattern in my local node_modules and solved this problem in React app.
But I finded this precription for a long time, because no one issues not closed.

Best regards, Anela.

**Comment by rekmarks** [comment] 2018-10-17 14:45
Issue not fully resolved on my end after applying @spirosbax's fix manually. See: https://github.com/isaacs/node-graceful-fs/pull/135#issuecomment-430634423

**Comment by DevCubeHD** [comment] 2018-10-25 12:41
@rekmarks yeah, just think about using git... nobody would ever include the node_modues folder

**Comment by coreyfarrell** [comment] 2020-05-07 13:46
This issue should be resolved by latest graceful-fs. Please let us know if you continue to have problems after updating.

**Closed by coreyfarrell** 2020-05-07 13:46 UTC
