### ISSUE TITLE
npm v5.0.3 installation integrity checksum failure

### ISSUE THREAD

**Issue by AsherKa** [isaacs/node-graceful-fs#114] opened 2017-06-26 10:26 UTC
I'm trying to install graceful-fs@1.2.3 and getting an integrity checksum failure,

``` 
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! code EINTEGRITY
npm ERR! sha1-D5CPr05uwCUk5UpX5DLFwBPgjJ8= integrity checksum failed when using sha1: wanted sha1-D5CPr05uwCUk5UpX5DLFwBPgjJ8= but got sha1-qvKjpvEcAjxqxMfh5/DcmcyrYjA=. (13914360 bytes)
```
Only happens with npm v5

Anyone else facing this issue?

**Comment by iarna** [comment] 2017-07-02 05:59
The integrity failure isn't on `graceful-fs`.  The warning from `graceful-fs` that you're quoting was just coincidentally near the integrity failure.

Here's how I know that:

The most straightforward pointer was that the thing with the integrity failure is reported as 13 MB (`13914360 bytes`). That's MUCH larger than any version of `graceful-fs`. 1.2.3 in particular is 5kb.

I also tried installing that version of `graceful-fs` elsewhere and it's integrity is `sha1-FaSAaldUfLLS2/J/QuiajDRRs2Q=`.

**Comment by coreyfarrell** [comment] 2021-03-05 13:21
Since graceful-fs doesn't install itself this is not a bug here.  Possibly an issue with an old version of npm or maybe you hit a corrupt npm cache.

Closing this bug, if you experience again this is probably something to open a discussion at https://github.com/npm/feedback/discussions/.

**Closed by coreyfarrell** 2021-03-05 13:21 UTC
