### ISSUE TITLE
Release 4.1.7 causes TypeError: Cannot read property 'uid' of undefined

### ISSUE THREAD

**Issue by rasmuskl** [isaacs/node-graceful-fs#89] opened 2016-09-26 21:59 UTC
Started getting this error right now and noticed that the only difference in my builds was the new version of graceful-fs 4.1.7, which was released 20 min ago...

```
> cross-env NODE_ENV=production webpack --display-chunks --progress
C:\a\1\s\Source\PoeStats\node_modules\graceful-fs\polyfills.js:264
      if (stats.uid < 0) stats.uid += 0x100000000
               ^
TypeError: Cannot read property 'uid' of undefined
    at C:\a\1\s\Source\PoeStats\node_modules\graceful-fs\polyfills.js:264:16
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by ztolley** [comment] 2016-09-26 22:00
Same here

**Comment by satazor** [comment] 2016-09-26 22:01
Same here: https://travis-ci.org/IndigoUnited/node-proper-lockfile/jobs/162917033

**Comment by MarkPieszak** [comment] 2016-09-26 22:02
Same, happening during a `webpack` build.

![image](https://cloud.githubusercontent.com/assets/2574412/18853489/6440a9c8-8413-11e6-92b3-987ad8c0953c.png)

**Comment by mordocai** [comment] 2016-09-26 22:03
Duplicate of #88

**Comment by mordocai** [comment] 2016-09-26 22:08
@ztolley You can get around this kind of stuff with some nasty npm shrinkwrap hacks but I'd recommend waiting if you can.

**Comment by MarkPieszak** [comment] 2016-09-26 22:09
v4.1.8 fixed the problem, we're all set now 👍 💯 

https://github.com/isaacs/node-graceful-fs/releases

**Comment by gzurbach** [comment] 2016-09-26 22:12
Thanks guys for the quick turnaround!

**Comment by dschoeni** [comment] 2016-09-26 22:14
fixed it for me as well, thanks for the quick reaction!

**Comment by 4ossiblellc** [comment] 2016-09-26 22:26
![output_dgdbwh](https://cloud.githubusercontent.com/assets/13743621/18854056/9628b7ac-83fd-11e6-9cec-3ad519b5e78d.gif)

**Closed** 2016-09-27 16:51 UTC
